cask_args appdir: "/Applications"

tap "hashicorp/tap"

brew "atuin"
brew "coreutils"
brew "delve"
brew "direnv"
brew "fd"
brew "fzf"
brew "gh"
brew "git", link: true
brew "git-lfs"
brew "hashicorp/tap/packer"
brew "hermit"
brew "JetBrains/utils/kotlin-lsp"
brew "jq"
brew "libyaml"
brew "luarocks"
brew "make", link: true
brew "mint"
brew "mise"
brew "neovim"
brew "pipx"
brew "pre-commit"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "tree-sitter"
brew "tree-sitter-cli"
brew "wakeonlan"
brew "zoxide"

cask "1password-cli"
cask "container"
cask "devcleaner"
cask "google-chrome"
cask "karabiner-elements"
cask "keepingyouawake"
cask "iterm2"
cask "mitmproxy"
cask "obsidian"
cask "rectangle"
cask "xcodes-app"
