cask_args appdir: "/Applications"

tap "cirruslabs/cli"
tap "hashicorp/tap"

brew "cirruslabs/cli/tart"
brew "coreutils"
brew "fd"
brew "fzf"
brew "gh"
brew "git", link: true
brew "git-lfs"
brew "go"
brew "hashicorp/tap/packer"
brew "jenv"
brew "jq"
brew "luarocks"
brew "make", link: true
brew "mint"
brew "neovim"
brew "pipx"
brew "rbenv"
brew "rg"
brew "ripgrep"
brew "tmux"
brew "xcbeautify"
brew "xcode-build-server"
brew "wakeonlan"

cask "1password-cli"
cask "container"
cask "corretto@21"
cask "karabiner-elements"
cask "keepingyouawake"
cask "iterm2"
cask "mitmproxy"
cask "obsidian"
cask "rectangle"
cask "xcodes"
cask "zulu@17"
