[tools]
go = "latest"
java = ["corretto-21", "zulu-17"]
node = { version = "22.19.0", postinstall = "npm install -g @devcontainers/cli @elgato/cli npm@11.4.2" }
ruby = { version = "3.4.4", postinstall = "gem install xcodeproj" }
"ubi:withered-magic/starpls" = "latest"
