bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set-option -g focus-events on
set-window-option -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g mouse on
set -g focus-events on

# Active pane highlighting
set -g pane-active-border-style "fg=green,bold"
set -g pane-border-style "fg=colour238"
set -g pane-border-indicators both
set -g window-style "bg=colour236"
set -g window-active-style "bg=black"

set -s extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
